title: Casey Weed
email: casey@caseyweed.com
# description: >-
baseurl: ""
url: ""
github_username: battleroid
repository: battleroid/battleroid.github.io

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - rouge

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Casey Weed"

# exclude: {}
